/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.iwms.deep;import cn.zhuatech.iwms.model.AuditLog;import cn.zhuatech.iwms.repository.AuditLogRepository;import jakarta.persistence.*;import jakarta.validation.constraints.*;import org.springframework.http.HttpStatus;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.server.ResponseStatusException;import java.time.*;import java.util.*;
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@Service @Transactional(readOnly=true) public class DeepDomainService{private final EntityManager em;private final AuditLogRepository logs;/**
                                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                            */
public DeepDomainService(EntityManager e,AuditLogRepository l){em=e;logs=l;}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 public Dashboard dashboard(String org){return new Dashboard(assets(org),orders(org),requests(org));}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public AssetView createAsset(AssetRequest r){if(findAsset(r.organizationCode(),r.assetNo())!=null)throw conflict("设施资产编号已存在");var a=new FacilityAsset(r.organizationCode(),r.assetNo(),r.name(),r.location(),r.criticality(),r.warrantyEnd());em.persist(a);audit("FACILITY_ASSET","登记设施资产",a.assetNo,a.location);return view(a);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public AssetView activate(Long id){var a=asset(id);if(!"DRAFT".equals(a.status))throw conflict("只有草稿资产可以启用");a.status="ACTIVE";audit("FACILITY_ASSET","启用设施资产",a.assetNo,a.criticality);return view(a);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public PlanView createPlan(Long id,PlanRequest r){var a=asset(id);if(!"ACTIVE".equals(a.status))throw conflict("只有启用资产可以建立保养计划");if(r.intervalDays()<1)throw bad("保养周期至少1天");var p=new MaintenancePlan(id,r.planNo(),r.intervalDays(),r.checklist(),r.nextDueDate());em.persist(p);audit("MAINTENANCE_PLAN","建立保养计划",p.planNo,a.assetNo);return view(p);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public WorkOrderView generate(Long planId,GenerateRequest r){var p=plan(planId);if(!"ACTIVE".equals(p.status))throw conflict("保养计划未启用");if(r.dueDate().isBefore(LocalDate.now()))throw bad("工单到期日不能早于当前日期");var w=new MaintenanceWorkOrder(planId,p.assetId,r.workOrderNo(),r.priority(),r.dueDate());em.persist(w);p.nextDueDate=r.dueDate().plusDays(p.intervalDays);audit("MAINTENANCE_ORDER","生成保养工单",w.workOrderNo,p.planNo);return view(w);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public WorkOrderView assign(Long id,AssignRequest r){var w=order(id);state(w,"OPEN");w.assignee=r.assignee();w.status="ASSIGNED";audit("MAINTENANCE_ORDER","分派工单",w.workOrderNo,r.assignee());return view(w);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public WorkOrderView start(Long id){var w=order(id);state(w,"ASSIGNED");w.status="IN_PROGRESS";audit("MAINTENANCE_ORDER","开始作业",w.workOrderNo,w.assignee);return view(w);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public WorkOrderView complete(Long id,CompleteRequest r){var w=order(id);state(w,"IN_PROGRESS");var a=asset(w.assetId);if(r.meterReading()<a.currentMeter)throw conflict("本次读数不能小于资产历史读数");w.meterReading=r.meterReading();w.completionNote=r.note();w.status="WAITING_ACCEPTANCE";audit("MAINTENANCE_ORDER","提交完工",w.workOrderNo,r.note());return view(w);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public WorkOrderView accept(Long id,AcceptRequest r){var w=order(id);state(w,"WAITING_ACCEPTANCE");if(r.accepted()){w.status="CLOSED";var a=asset(w.assetId);a.currentMeter=w.meterReading;}else{w.status="IN_PROGRESS";}audit("MAINTENANCE_ORDER",r.accepted()?"验收通过":"验收退回",w.workOrderNo,r.note());return view(w);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public RequestView serviceRequest(ServiceRequestInput r){int minutes=switch(r.priority()){case "P1"->30;case "P2"->120;case "P3"->480;default->1440;};var x=new FacilityServiceRequest(r.organizationCode(),r.requestNo(),r.category(),r.priority(),r.description(),r.location(),LocalDateTime.now().plusMinutes(minutes));em.persist(x);audit("FACILITY_SERVICE","受理服务请求",x.requestNo,x.priority);return view(x);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public int escalate(String org,LocalDateTime asOf){var list=em.createQuery("select r from FacilityServiceRequest r where r.organizationCode=:o and r.status='OPEN' and r.dueAt<:t and r.escalated=false",FacilityServiceRequest.class).setParameter("o",org).setParameter("t",asOf).getResultList();list.forEach(x->{x.escalated=true;audit("FACILITY_SERVICE","SLA升级",x.requestNo,x.location);});return list.size();}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 private List<AssetView> assets(String o){return em.createQuery("select a from FacilityAsset a where a.organizationCode=:o order by a.createdAt desc",FacilityAsset.class).setParameter("o",o).getResultList().stream().map(this::view).toList();}/**
                                                                                                                                                                                                                                                   * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                   */
private List<WorkOrderView> orders(String o){return em.createQuery("select w from MaintenanceWorkOrder w where w.assetId in(select a.id from FacilityAsset a where a.organizationCode=:o) order by w.createdAt desc",MaintenanceWorkOrder.class).setParameter("o",o).getResultList().stream().map(this::view).toList();}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           */
private List<RequestView> requests(String o){return em.createQuery("select r from FacilityServiceRequest r where r.organizationCode=:o order by r.createdAt desc",FacilityServiceRequest.class).setParameter("o",o).getResultList().stream().map(this::view).toList();}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 private FacilityAsset asset(Long id){var x=em.find(FacilityAsset.class,id);if(x==null)throw missing("设施资产不存在");return x;}/**
                                                                                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                           */
private MaintenancePlan plan(Long id){var x=em.find(MaintenancePlan.class,id);if(x==null)throw missing("保养计划不存在");return x;}/**
                                                                                                                                                                                                                                                       * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                       */
private MaintenanceWorkOrder order(Long id){var x=em.find(MaintenanceWorkOrder.class,id);if(x==null)throw missing("工单不存在");return x;}/**
                                                                                                                                                                                                                                                                                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                            */
private FacilityAsset findAsset(String o,String n){return em.createQuery("select a from FacilityAsset a where a.organizationCode=:o and a.assetNo=:n",FacilityAsset.class).setParameter("o",o).setParameter("n",n).getResultStream().findFirst().orElse(null);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           */
private void state(MaintenanceWorkOrder w,String s){if(!s.equals(w.status))throw conflict("当前工单状态不能执行该操作");}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       */
private void audit(String m,String a,String n,String d){logs.save(new AuditLog(m,a,n,"iwms-domain",d));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               */
private ResponseStatusException bad(String m){return new ResponseStatusException(HttpStatus.BAD_REQUEST,m);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           */
private ResponseStatusException conflict(String m){return new ResponseStatusException(HttpStatus.CONFLICT,m);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         */
private ResponseStatusException missing(String m){return new ResponseStatusException(HttpStatus.NOT_FOUND,m);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 private AssetView view(FacilityAsset a){return new AssetView(a.id,a.organizationCode,a.assetNo,a.name,a.location,a.criticality,a.status,a.currentMeter,a.warrantyEnd,a.version);}/**
                                                                                                                                                                                   * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                   */
private PlanView view(MaintenancePlan p){return new PlanView(p.id,p.assetId,p.planNo,p.intervalDays,p.checklist,p.nextDueDate,p.status);}/**
                                                                                                                                                                                                                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                            */
private WorkOrderView view(MaintenanceWorkOrder w){return new WorkOrderView(w.id,w.assetId,w.planId,w.workOrderNo,w.priority,w.status,w.assignee,w.dueDate,w.meterReading,w.completionNote,w.version);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   */
private RequestView view(FacilityServiceRequest r){return new RequestView(r.id,r.organizationCode,r.requestNo,r.category,r.priority,r.description,r.location,r.status,r.dueAt,r.escalated);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 public record AssetRequest(@NotBlank String organizationCode,@NotBlank String assetNo,@NotBlank String name,@NotBlank String location,@NotBlank String criticality,LocalDate warrantyEnd){}/**
                                                                                                                                                                                             * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                             */
public record PlanRequest(@NotBlank String planNo,@Positive int intervalDays,@NotBlank String checklist,@NotNull LocalDate nextDueDate){}/**
                                                                                                                                                                                                                                                                                                                                      * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                      */
public record GenerateRequest(@NotBlank String workOrderNo,@NotBlank String priority,@NotNull LocalDate dueDate){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                        * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                        */
public record AssignRequest(@NotBlank String assignee){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                */
public record CompleteRequest(@PositiveOrZero double meterReading,@NotBlank String note){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          */
public record AcceptRequest(boolean accepted,@NotBlank String note){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               */
public record ServiceRequestInput(@NotBlank String organizationCode,@NotBlank String requestNo,@NotBlank String category,@NotBlank String priority,@NotBlank String description,@NotBlank String location){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           */
public record AssetView(Long id,String organizationCode,String assetNo,String name,String location,String criticality,String status,double currentMeter,LocalDate warrantyEnd,long version){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        */
public record PlanView(Long id,Long assetId,String planNo,int intervalDays,String checklist,LocalDate nextDueDate,String status){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          */
public record WorkOrderView(Long id,Long assetId,Long planId,String workOrderNo,String priority,String status,String assignee,LocalDate dueDate,double meterReading,String completionNote,long version){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   */
public record RequestView(Long id,String organizationCode,String requestNo,String category,String priority,String description,String location,String status,LocalDateTime dueAt,boolean escalated){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       */
public record Dashboard(List<AssetView> assets,List<WorkOrderView> workOrders,List<RequestView> serviceRequests){}
}
