/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.iwms.deep;import cn.zhuatech.iwms.common.ApiResponse;import jakarta.validation.Valid;import org.springframework.web.bind.annotation.*;import java.time.*;
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@RestController @RequestMapping("/api/facility-ops") public class DeepDomainController{private final DeepDomainService s;/**
                                                                                                                          * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                          */
public DeepDomainController(DeepDomainService s){this.s=s;}/**
                                                                                                                                                                                     * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                     */
@GetMapping("/dashboard")ApiResponse<?> dashboard(@RequestParam String organizationCode){return ApiResponse.ok(s.dashboard(organizationCode));}/**
                                                                                                                                                                                                                                                                                                                                    * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                    */
@PostMapping("/assets")ApiResponse<?> asset(@Valid @RequestBody DeepDomainService.AssetRequest r){return ApiResponse.ok(s.createAsset(r));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                               * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                               */
@PostMapping("/assets/{id}/plans")ApiResponse<?> plan(@PathVariable Long id,@Valid @RequestBody DeepDomainService.PlanRequest r){return ApiResponse.ok(s.createPlan(id,r));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           */
@PostMapping("/plans/{id}/work-orders")ApiResponse<?> generate(@PathVariable Long id,@Valid @RequestBody DeepDomainService.GenerateRequest r){return ApiResponse.ok(s.generate(id,r));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  */
@PostMapping("/work-orders/{id}/assign")ApiResponse<?> assign(@PathVariable Long id,@Valid @RequestBody DeepDomainService.AssignRequest r){return ApiResponse.ok(s.assign(id,r));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    */
@PostMapping("/work-orders/{id}/start")ApiResponse<?> start(@PathVariable Long id){return ApiResponse.ok(s.start(id));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           */
@PostMapping("/work-orders/{id}/complete")ApiResponse<?> complete(@PathVariable Long id,@Valid @RequestBody DeepDomainService.CompleteRequest r){return ApiResponse.ok(s.complete(id,r));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     */
@PostMapping("/service-requests")ApiResponse<?> request(@Valid @RequestBody DeepDomainService.ServiceRequestInput r){return ApiResponse.ok(s.serviceRequest(r));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */
@PostMapping("/sla/escalate")ApiResponse<?> escalate(@RequestParam String organizationCode,@RequestParam LocalDateTime asOf){return ApiResponse.ok(s.escalate(organizationCode,asOf));}}
