/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.iwms.deep;import jakarta.persistence.*;import java.time.*;
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@Entity @Table(name="iw_facility_assets",uniqueConstraints=@UniqueConstraint(columnNames={"organizationCode","assetNo"})) class FacilityAsset{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;@Version long version;@Column(nullable=false,length=40)String organizationCode;@Column(nullable=false,length=50)String assetNo;@Column(nullable=false,length=120)String name;@Column(nullable=false,length=100)String location;@Column(nullable=false,length=30)String criticality;@Column(nullable=false,length=20)String status="DRAFT";double currentMeter;LocalDate warrantyEnd;LocalDateTime createdAt;/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        */
protected FacilityAsset(){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   */
FacilityAsset(String o,String n,String name,String l,String c,LocalDate w){organizationCode=o;assetNo=n;this.name=name;location=l;criticality=c;warrantyEnd=w;createdAt=LocalDateTime.now();}}
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@Entity @Table(name="iw_maintenance_plans",uniqueConstraints=@UniqueConstraint(columnNames={"assetId","planNo"})) class MaintenancePlan{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;@Column(nullable=false)Long assetId;@Column(nullable=false,length=50)String planNo;int intervalDays;@Column(nullable=false,length=300)String checklist;LocalDate nextDueDate;@Column(nullable=false,length=20)String status="ACTIVE";/**
                                                                                                                                                                                                                                                                                                                                                                                                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                           */
protected MaintenancePlan(){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        */
MaintenancePlan(Long a,String n,int i,String c,LocalDate d){assetId=a;planNo=n;intervalDays=i;checklist=c;nextDueDate=d;}}
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@Entity @Table(name="iw_work_orders",uniqueConstraints=@UniqueConstraint(columnNames="workOrderNo")) class MaintenanceWorkOrder{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;@Version long version;Long planId;@Column(nullable=false)Long assetId;@Column(nullable=false,length=50)String workOrderNo;@Column(nullable=false,length=20)String priority;@Column(nullable=false,length=20)String status="OPEN";@Column(length=50)String assignee;LocalDate dueDate;double meterReading;@Column(length=500)String completionNote;LocalDateTime createdAt;/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        */
protected MaintenanceWorkOrder(){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          */
MaintenanceWorkOrder(Long p,Long a,String n,String pr,LocalDate d){planId=p;assetId=a;workOrderNo=n;priority=pr;dueDate=d;createdAt=LocalDateTime.now();}}
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@Entity @Table(name="iw_service_requests",uniqueConstraints=@UniqueConstraint(columnNames="requestNo")) class FacilityServiceRequest{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;@Column(nullable=false,length=40)String organizationCode;@Column(nullable=false,length=50)String requestNo;@Column(nullable=false,length=30)String category;@Column(nullable=false,length=20)String priority;@Column(nullable=false,length=300)String description;@Column(nullable=false,length=100)String location;@Column(nullable=false,length=20)String status="OPEN";LocalDateTime dueAt;boolean escalated;LocalDateTime createdAt;/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           */
protected FacilityServiceRequest(){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               */
FacilityServiceRequest(String o,String n,String c,String p,String d,String l,LocalDateTime due){organizationCode=o;requestNo=n;category=c;priority=p;description=d;location=l;dueAt=due;createdAt=LocalDateTime.now();}}
